trigger:
- main   # or your preferred branch

variables:
  TF_VERSION: '1.5.7'

  # Azure Service Principal credentials
  ARM_CLIENT_ID: '76d3056e-1da2-4b5c-b055-1d674064bdd2'
  ARM_CLIENT_SECRET: 'oOO8Q~nKxDJIqwcSmGk3V97hRKd-sf-ARpIepcJi'  # Best to move to secret variables in real usage
  ARM_SUBSCRIPTION_ID: 'd5f5198e-d19e-4e8b-83d1-f8c080acf8fe'
  ARM_TENANT_ID: 'df28c44c-39ef-499f-bdf4-3fc2656e6d00'

stages:
- stage: Terraform
  jobs:
  - job: RunTerraform
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: UseTerraform@0
      inputs:
        terraformVersion: '$(TF_VERSION)'

    - script: terraform --version
      displayName: 'Show Terraform Version'

    - script: |
        cd terraform
        terraform init
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan
      displayName: 'Terraform Init, Plan & Apply'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
